// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           42
// Async Callback:                       1
// Total number of exported functions:  44

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tester_contract
    (
        init => init
        getSum => sum
        add => add
        noArgNoReturnEndpoint => no_arg_no_return_endpoint
        returnCaller => return_caller
        returnManagedBuffer => return_managed_buffer
        returnContractAddress => return_contract_address
        returnBiguint => return_biguint
        returnU8 => return_u8
        returnU16 => return_u16
        returnU32 => return_u32
        returnU64 => return_u64
        returnU32Vec => return_u32_vec
        returnU64Vec => return_u64_vec
        returnBufferVec => return_buffer_vec
        returnBiguintVec => return_biguint_vec
        returnTwoU64 => return_two_u64
        returnTwoBuffers => return_two_buffers
        returnOneBufferOneU64AndOneBiguint => return_one_buffer_one_u64_and_one_buffer
        returnDoubleOfU64Arg => return_double_of_u64_arg
        returnDoubleOfBiguintArg => return_double_of_biguint_arg
        returnAppendedBufferArg => return_appended_buffer_arg
        returnSumTwoBiguintArgs => return_sum_two_biguint_args
        returnConcatMultiBufferArgs => return_concat_multi_buffer_args
        returnSumMultiU64Args => return_sum_multi_u64_args
        returnSumMultiBiguintArgs => return_sum_multi_biguint_args
        returnCustomStruct => return_custom_struct
        returnCustomStructArg => return_custom_struct_arg
        returnCustomStructWithStructAndVec => return_custom_struct_with_struct_and_vec
        returnCustomStructWithStructAndVecArg => return_custom_struct_with_struct_and_vec_arg
        returnCustomEnum => return_custom_enum
        returnCustomEnumArg => return_custom_enum_arg
        returnFirstCustomEnumWithValues => return_first_custom_enum_with_values
        returnSecondCustomEnumWithValues => return_second_custom_enum_with_values
        returnCustomEnumWithValuesArg => return_custom_enum_with_values_arg
        returnFirstCustomEnumWithFields => return_first_custom_enum_with_fields
        returnSecondCustomEnumWithFields => return_second_custom_enum_with_fields
        returnCustomEnumWithFieldsArg => return_custom_enum_with_fields_arg
        returnMultiValueTwo => return_optional_multi_value_three_arg
        callAnotherContractReturnTwoU64 => call_another_contract_return_u64
        asyncCallAnotherContractReturnTwoU64NoCallback => async_call_another_contract_return_u64_no_callback
        asyncCallAnotherContractReturnTwoU64WithReturningCallback => async_call_another_contract_return_u64_with_returning_callback
        asyncCallAnotherContractReturnTwoU64WithNonReturningCallback => async_call_another_contract_return_u64_with_non_returning_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { tester_contract }
