[workspace]
resolver = "2"

exclude = [
    "cookbook/deps"
]

members = [
    "account",
    "data",
    "executor",
    "mocking",
    "caching",
    "request",
    "token",
    "multisig",
    "tester/core",
    "tester/contract",
    "tester/contract/meta"
]
