[package]
name = "novax-token"
version = "0.2.7"
edition = "2021"
license = "GPL-3.0-only"
description = "The `novax-token` crate offers utilities for retrieving token information from the blockchain, such as querying address balances, token metadata, and other related operations. By encapsulating the logic for interacting with token-related blockchain features, `novax-token` simplifies the process of querying and managing tokens within decentralized applications, making it a valuable tool for developers working with blockchain tokens and assets."
repository = "https://github.com/gfusee/novax"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.188"
serde_json = "1.0.105"
hex = "0.4.3"
novax = { path = "../core", version = "0.2.7" }
novax-data = { path = "../data", version = "0.2.7" }
novax-request = { path = "../request", version = "0.2.7" }
num-bigint = "0.4.4"
async-trait = "0.1.73"
multiversx-sc = "=0.57.1"
multiversx-sc-scenario = "=0.57.1"
multiversx-sc-codec = "=0.22.0"
base64 = "0.21.5"

[dev-dependencies]
tokio = "1.32.0"
async-trait = "0.1.73"
hyper = "1.1.0"
http = "1.1.0"

