pub const DEPLOY_BYTES_SHOULD_BE_AN_ADDRESS: &str = "NOVAX_MULTISIG_DEPLOY_BYTES_SHOULD_BE_AN_ADDRESS";
pub const NONE_PROPOSAL_ID_ERROR: &str = "NOVAX_MULTISIG_NONE_PROPOSAL_ID_ERROR";
pub const NO_ACTION_FOUND_FOR_ID_ERROR: &str = "NOVAX_MULTISIG_NO_ACTION_FOUND_FOR_ID_ERROR";
pub const ERROR_WHILE_RETRIEVING_QUORUM: &str = "NOVAX_MULTISIG_ERROR_WHILE_PERFORMING_ACTION_TRANSACTION";
pub const ERROR_WHILE_RETRIEVING_FULL_ACTION_FULL_INFO: &str = "NOVAX_MULTISIG_ERROR_WHILE_RETRIEVING_FULL_ACTION_FULL_INFO";
pub const ERROR_WHILE_PROPOSING_ACTION_TRANSACTION: &str = "NOVAX_MULTISIG_ERROR_WHILE_PROPOSING_ACTION_TRANSACTION";
pub const ERROR_WHILE_PERFORMING_ACTION_TRANSACTION: &str = "NOVAX_MULTISIG_ERROR_WHILE_PERFORMING_ACTION_TRANSACTION";
pub const NO_DEPLOYED_ADDRESS: &str = "NOVAX_MULTISIG_NO_DEPLOYED_ADDRESS";
