[package]
name = "contract-meta"
version = "0.2.7"
edition = "2021"
publish = false

[dependencies.tester-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.57.1"
default-features = false
