[package]
name = "contract-meta"
version = "0.2.1"
edition = "2021"
publish = false

[dependencies.tester-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.3"
default-features = false
